project: 'drift2'
exp_name: 'pdbbind_affinity'
checkpoints: models
logs: logs
device: gpu
log_iterations: 20
wandb_entity: null
enable_progress_bar: True

# Model parameters
lr: 2.0e-4
batch_size: 4
n_layers: 24
n_epochs: 2000
test_epochs: 20
n_stability_samples: 1
nf: 64
activation: silu
sin_embedding: False
normalization_factor: 100
aggregation_method: 'sum'
data_augmentation: True
table_name: 'pdbbind_dataset'
use_affinity_mode: true  # Enable affinity mode
